packages:
  - '!docs/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
overrides:
  '@nuxt/kit': 4.4.5
  '@vueuse/core': 14.3.0
  svix: ^1.92.2
