name: Security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '24 4 * * 1'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2

  codeql:
    name: CodeQL
    if: github.event.repository.private == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: github/codeql-action/init@53e96ec3b35fce51c141c0d6f0e31028a448722d # v3
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: javascript-typescript
      - uses: github/codeql-action/analyze@53e96ec3b35fce51c141c0d6f0e31028a448722d # v3

  scorecard:
    name: Scorecard
    if: github.event.repository.private == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false
      - uses: github/codeql-action/upload-sarif@53e96ec3b35fce51c141c0d6f0e31028a448722d # v3
        with:
          sarif_file: results.sarif
